TEXT_TYPES = [
    'No style',
    'Conspiracy theories',
    'TV-reports',
    'Toast',
    'Boy quotes',
    'Advertising slogans',
    'Short stories',
    'Instagram signatures',
    'Wikipedia',
    'Movie synopsis',
    'Horoscope',
    'Folk wisdom',
    'Garage',
]
